name: OWASP Dependency Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    schedule:
      - cron: '0 12 * * 1'

jobs:
  dependency-check:
    name: Run OWASP Dependency Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Dependency-Check-Scan
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "AwesomeToDo"
          path: "."
          format: "HTML"
          out: "reports"
          args: "--enableExperimental"

      - name: Upload Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports
