name: Docker CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Start Docker Compose services
        run: docker compose up -d --build
      - name: Install Composer dependencies
        run: docker compsoe exec app composer install
      - name: Run PHPUnit Tests
        run: docker compose exec app ./vendor/bin/phpunit --configuration phpunit.xml

